// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Models;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241211162611_Film")]
    partial class Film
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Models.Acteurs", b =>
                {
                    b.Property<int>("ActeurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActeurID"));

                    b.Property<DateTime>("date_naissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("nationalite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ActeurID");

                    b.ToTable("acteurs");
                });

            modelBuilder.Entity("Project.Models.Categories", b =>
                {
                    b.Property<int>("CategorieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieID"));

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategorieID");

                    b.HasIndex("nom")
                        .IsUnique();

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Project.Models.Editeurs", b =>
                {
                    b.Property<int>("EditeurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EditeurID"));

                    b.Property<DateTime>("date_naissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("nationalite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EditeurID");

                    b.ToTable("editeurs");
                });

            modelBuilder.Entity("Project.Models.Film", b =>
                {
                    b.Property<int>("FilmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmID"));

                    b.Property<int>("ActeurPID")
                        .HasColumnType("int");

                    b.Property<int>("ActeurSID")
                        .HasColumnType("int");

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.Property<int>("DateCreated")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<int>("EditeurID")
                        .HasColumnType("int");

                    b.Property<int>("LangueID")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("realisateurID")
                        .HasColumnType("int");

                    b.HasKey("FilmID");

                    b.HasIndex("ActeurPID");

                    b.HasIndex("ActeurSID");

                    b.HasIndex("CategorieID");

                    b.HasIndex("EditeurID");

                    b.HasIndex("LangueID");

                    b.HasIndex("realisateurID");

                    b.ToTable("films");
                });

            modelBuilder.Entity("Project.Models.Langues", b =>
                {
                    b.Property<int>("LanguesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguesID"));

                    b.Property<string>("langues")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LanguesID");

                    b.ToTable("langues");
                });

            modelBuilder.Entity("Project.Models.Realisateurs", b =>
                {
                    b.Property<int>("RealisateursID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RealisateursID"));

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RealisateursID");

                    b.ToTable("realisateurs");
                });

            modelBuilder.Entity("Project.Models.Film", b =>
                {
                    b.HasOne("Project.Models.Acteurs", "ActeurPrincipal")
                        .WithMany()
                        .HasForeignKey("ActeurPID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Acteurs", "ActeurSecondaire")
                        .WithMany()
                        .HasForeignKey("ActeurSID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Editeurs", "Editeur")
                        .WithMany()
                        .HasForeignKey("EditeurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Langues", "langues")
                        .WithMany()
                        .HasForeignKey("LangueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Realisateurs", "Realisateurs")
                        .WithMany()
                        .HasForeignKey("realisateurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActeurPrincipal");

                    b.Navigation("ActeurSecondaire");

                    b.Navigation("Categories");

                    b.Navigation("Editeur");

                    b.Navigation("Realisateurs");

                    b.Navigation("langues");
                });
#pragma warning restore 612, 618
        }
    }
}
